# Generated by Django 5.0.1 on 2024-02-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitob',
            name='file',
            field=models.FileField(default=1, upload_to='uploads'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kitob',
            name='yil',
            field=models.DateField(),
        ),
    ]
